### ISSUE TITLE
关于接入大华实时流数返回

### ISSUE THREAD

**Issue by WuYuansen** [clpz299/monitor#1]
您好，请问您知道怎么获取大华实时流视频数据返回到前端嘛？

**Comment by clpz299** [comment]
看大华是否提供实时流接口，通过转码成rtmp向前端推送




------------------ 原始邮件 ------------------
发件人: "Mr. Wu"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 晚上6:59
收件人: "clpz299/monitor"<monitor@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [clpz299/monitor] 关于接入大华实时流数返回 (#1)




您好，请问您知道怎么获取大华实时流视频数据返回到前端嘛？

**Comment by WuYuansen** [comment]
他有实时流的返回。有微信或者qq嘛 方便交流。我是不知道怎么去接 有点懵 大华提供rtsp流地址


|
回到原点时，还能遇见你么？
|




在2019年10月23日 14:50，clpz299<notifications@github.com> 写道：
看大华是否提供实时流接口，通过转码成rtmp向前端推送




------------------ 原始邮件 ------------------
发件人: "Mr. Wu"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 晚上6:59
收件人: "clpz299/monitor"<monitor@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [clpz299/monitor] 关于接入大华实时流数返回 (#1)




您好，请问您知道怎么获取大华实时流视频数据返回到前端嘛？

**Comment by clpz299** [comment]
1648737500

**Comment by clpz299** [comment]
javacv




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr. Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 下午4:51
收件人:&nbsp;"clpz299/monitor"<monitor@noreply.github.com&gt;;
抄送:&nbsp;"⚜"<1648737500@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [clpz299/monitor] 关于接入大华实时流数返回 (#1)



他有实时流的返回。有微信或者qq嘛 方便交流。我是不知道怎么去接 有点懵 大华提供rtsp流地址
 
 
 |
 回到原点时，还能遇见你么？
 |
 
 
 
 
 在2019年10月23日 14:50，clpz299<notifications@github.com&gt; 写道：
 看大华是否提供实时流接口，通过转码成rtmp向前端推送
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人: "Mr. Wu"<notifications@github.com&gt;;
 发送时间: 2019年10月22日(星期二) 晚上6:59
 收件人: "clpz299/monitor"<monitor@noreply.github.com&gt;;
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
 主题: [clpz299/monitor] 关于接入大华实时流数返回 (#1)
 
 
 
 
 您好，请问您知道怎么获取大华实时流视频数据返回到前端嘛？
