### ISSUE TITLE
jave-1.0.2.jar

### ISSUE THREAD

**Issue by YukiYlf** [clpz299/monitor#3]
这个文件是哪里的？

**Comment by YukiYlf** [comment]
这个文件是否考虑用ffmepg来替换？

**Comment by YukiYlf** [comment]
![image](https://user-images.githubusercontent.com/55609473/85920661-1ab04e80-b8a8-11ea-8106-5f2df4ee80fd.png)

**Comment by YukiYlf** [comment]
上面可以工具得到--问题不大

**Comment by YukiYlf** [comment]
![image](https://user-images.githubusercontent.com/55609473/85920689-6cf16f80-b8a8-11ea-87bf-f62469e39c92.png)

**Comment by YukiYlf** [comment]
配置情况

**Comment by YukiYlf** [comment]
![image](https://user-images.githubusercontent.com/55609473/85920714-9c07e100-b8a8-11ea-8274-a1b6ff2a3669.png)

**Comment by YukiYlf** [comment]
这些错误可以解决的方法，-后面贴上来
希望这个可以开源可以做的比较好，还可以更好的展开相关的功能

**Comment by clpz299** [comment]
也许我可以单独开个链接将这些使用到的jar文件共享出来

**Comment by clpz299** [comment]
因为工作原因，这个项目并没有长时间维护，不过马上有时间去增加这里面的内容了，请期待。

**Comment by YukiYlf** [comment]
你放到LIB下面就可以阿
这样别人要使用也简单

**Comment by YukiYlf** [comment]
如果别人老调试不通，一般就是直接放弃了

**Comment by YukiYlf** [comment]
我刚好有做，所以看见你的这个部分，我是大华DEMO本身有，重写，所以看一下

**Comment by clpz299** [comment]
发布的时候没有考虑到，因为这几个jar还是很好找到的

**Comment by clpz299** [comment]
后面会补一份 md 文档上去，jar也会补充上去。

**Comment by YukiYlf** [comment]
是好找，但是如果正确引用，这些都是很重要的，特别是要做开源，这个方面很重要

**Comment by clpz299** [comment]
嗯嗯，受教受教

**Comment by YukiYlf** [comment]
这个方面开源不多，你可以尝试
你这个本身不错，但是访问的人太少了，要多维护才行

**Comment by clpz299** [comment]
会的，后续也会有新的项目开源出来，多多支持。
