### ISSUE TITLE
今天测试一下看

### ISSUE THREAD

**Issue by YukiYlf** [clpz299/monitor#6]
你这个视频是取得历史数据？

**Comment by clpz299** [comment]
嗯，整个程序当中涉及两个接口，一个接口是通过时间截取图片，另外一个接口是获取硬盘机的时间范围回放录像，你应该可以在实时截图接口中找到关于实时监控的sdk调用，或许你能提供关于一些常用到的接口，我这边可以进行更新开发

**Comment by YukiYlf** [comment]
刚好我项目都用到这2个类型的
海康大华车牌识别，人流监控，摄像机控制

**Comment by YukiYlf** [comment]
我这边常用接口是比较齐全的
我可以发你，直接使用SDK开发，推流，监听，这个方面

**Comment by YukiYlf** [comment]
在应用项目的实际场景

**Comment by YukiYlf** [comment]
你需要的发给你SDK
包括我有整理的，可以把这个做成比较不错的开源，目前这个方面还是比较少

**Comment by clpz299** [comment]
你也许可以开个分支，合并进来，或者你发邮件给我，我添加进去

**Comment by clpz299** [comment]
最近在做其他类型的研究，回复的会比较慢

**Comment by YukiYlf** [comment]
忙的要命，晚上回去给你ine




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clpz299/monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 晚上6:13
收件人:&nbsp;"clpz299/monitor"<monitor@noreply.github.com&gt;;
抄送:&nbsp;"快乐的小小鱼"<413166389@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [clpz299/monitor] 今天测试一下看 (#6)





 
Closed #6.
