### ISSUE TITLE
大华设备状态获取

### ISSUE THREAD

**Issue by Crazykulou** [clpz299/monitor#7]
目前监控也是用到海康和大华2家设备，海康获取设备状态已经实现，不知道大神是否解决过大华获取设备状态的需求或者是看到有相关文档，目前在sdk文档上未找到相关方法

**Comment by YukiYlf** [comment]
有的，我发给你。比较多
我都是源档，

**Comment by YukiYlf** [comment]
海康，大华，监听，摄像头，违停，车牌识别，都有做了商业上使用，可以发你核心代码，没事

**Comment by Crazykulou** [comment]
> 海康，大华，监听，摄像头，违停，车牌识别，都有做了商业上使用，可以发你核心代码，没事
可以呀，多谢了麻烦发我邮箱呗，wxwx5566@163.com

**Comment by clpz299** [comment]
> 目前监控也是用到海康和大华2家设备，海康获取设备状态已经实现，不知道大神是否解决过大华获取设备状态的需求或者是看到有相关文档，目前在sdk文档上未找到相关方法

我目前这里没有设备可以做开发，后面工作中有扩展会新增，后面我这边博客项目搭建完之后，你可以在我博客中找到文档，目前的文档都还未整理。

**Comment by YukiYlf** [comment]
公司最近特别忙，一直说给你代码弄过去， 还忙到没时间，周末给你

**Comment by YukiYlf** [comment]
只是推流视频部分，我是根据ffmepg来转的，
